const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "127.0.0.1:27000",
    basePath: "/",
    schemes: ['http'],
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/api/group/groupController.js']

swaggerAutogen(outputFile, endpointsFiles, doc)